spring:
  application:
    name: config #1
  profiles:
    active: dev #2native
  #热部署
  devtools:
    restart:
      enabled: true
      trigger-file: devtools.tg
  #cloud:
    #config:
      #server:
        #native:
          #search-locations: classpath:/config #1
  cloud:
      config:
        server:
          git:
            uri: https://github.com/tonypy/QianyiCloud #通过配置git 仓库地址读取配置文件
            search-paths: config/config
        label: master
server:
  port: 8888


