spring:
  redis:
    host: 192.168.99.100
    port: 6379
    password: 123456
    timeout:  5000
    database: 0  #连接数据库默认为0
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      max-idle: 8
      min-idle: 0
